name: Print Txt file

on:
    push:
        branches:
        - master
    pull_request:
        branches:
            - master

jobs:
    read_the_file:
        runs-on: ubuntu-latest
        steps:
            - name: Git Checkout Koran
              uses: actions/checkout@v2

            - name: Read the Txt file
              run: |
                ls -l
                cat tusar.txt